/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './client/public/**/*.{html,js}',
    './client/server/views/**/*.html',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#1A365D',
        'primary-container': '#2C5282',
        'primary-fixed': '#EBF8FF',
        'primary-fixed-dim': '#BEE3F8',
        'on-primary': '#FFFFFF',
        'on-primary-container': '#FFFFFF',
        'on-primary-fixed': '#1A365D',
        'on-primary-fixed-variant': '#2C5282',
        secondary: '#A81D23',
        'secondary-container': '#FED7D7',
        'secondary-fixed': '#FED7D7',
        'secondary-fixed-dim': '#FC8181',
        'on-secondary': '#FFFFFF',
        'on-secondary-container': '#A81D23',
        'on-secondary-fixed': '#A81D23',
        'on-secondary-fixed-variant': '#822727',
        tertiary: '#F8FAFC',
        'tertiary-container': '#EDF2F7',
        'tertiary-fixed': '#F8FAFC',
        'tertiary-fixed-dim': '#E2E8F0',
        'on-tertiary': '#1A365D',
        'on-tertiary-container': '#4A5568',
        'on-tertiary-fixed': '#1A365D',
        'on-tertiary-fixed-variant': '#4A5568',
        neutral: '#4A5568',
        background: '#F8FAFC',
        surface: '#FFFFFF',
        'surface-bright': '#F8FAFC',
        'surface-dim': '#CBD5E0',
        'surface-variant': '#E2E8F0',
        'surface-container': '#EDF2F7',
        'surface-container-low': '#F8FAFC',
        'surface-container-high': '#E2E8F0',
        'surface-container-highest': '#CBD5E0',
        'surface-container-lowest': '#FFFFFF',
        'surface-tint': '#1A365D',
        'on-surface': '#1A202C',
        'on-surface-variant': '#4A5568',
        'on-background': '#1A202C',
        outline: '#A0AEC0',
        'outline-variant': '#CBD5E0',
        'inverse-surface': '#1A365D',
        'inverse-on-surface': '#F8FAFC',
        'inverse-primary': '#90CDF4',
        error: '#A81D23',
        'error-container': '#FED7D7',
        'on-error': '#FFFFFF',
        'on-error-container': '#822727',
        blue: {
          50: '#F7FAFC',
          100: '#EBF8FF',
          200: '#BEE3F8',
          300: '#90CDF4',
          400: '#63B3ED',
          500: '#4299E1',
          600: '#3182CE',
          700: '#2C5282',
          800: '#1A365D',
          900: '#153E75',
        },
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        sm: '0.5rem',
        xl: '2.5rem',
        xs: '0.25rem',
        gutter: '24px',
        'container-max': '1280px',
        base: '4px',
        'sidebar-width': '260px',
        'margin-mobile': '16px',
        md: '1rem',
        lg: '1.5rem',
      },
      fontFamily: {
        'headline-sm': ['"IBM Plex Sans"', 'sans-serif'],
        'headline-md': ['"IBM Plex Sans"', 'sans-serif'],
        'headline-lg': ['"IBM Plex Sans"', 'sans-serif'],
        'headline-xl': ['"IBM Plex Sans"', 'sans-serif'],
        'headline-lg-mobile': ['"IBM Plex Sans"', 'sans-serif'],
        'headline-xl-mobile': ['"IBM Plex Sans"', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'label-sm': ['"JetBrains Mono"', 'monospace'],
        'label-md': ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-sm': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-xl': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-xl-mobile': ['30px', { lineHeight: '38px', fontWeight: '700' }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
